#!/usr/bin/env python3
"""Generate Claude, Codex, and OpenCode artifacts from agent-plugin.yaml files."""

from __future__ import annotations

import argparse
import difflib
import json
import shutil
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ROOT = ROOT / "plugins"
ROOT_MANIFEST = ROOT / ".agent-marketplace.yaml"
CODEX_MARKETPLACE = ROOT / ".agents" / "plugins" / "marketplace.json"
CLAUDE_MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
OPENCODE_ROOT = ROOT / "dist" / "opencode"
GENERATED_NOTE = "<!-- Generated by tools/generate-agent-marketplaces.py; edit the source command or agent-plugin.yaml instead. -->"


def main() -> None:
    args = parse_args()
    root_manifest, plugins = load_manifests()
    expected = build_expected_files(root_manifest, plugins)
    executable_files = build_expected_executable_files(plugins)

    if args.check:
        failures = check_expected_files(expected, executable_files)
        if failures:
            for failure in failures:
                print(failure, file=sys.stderr)
            raise SystemExit(1)
        print("Generated marketplace artifacts are up to date.")
        return

    if OPENCODE_ROOT.exists():
        shutil.rmtree(OPENCODE_ROOT)

    for path, content in expected.items():
        write_file(path, content)
    apply_executable_modes(executable_files)
    copy_opencode_skill_assets(plugins)
    print(f"Generated {len(expected)} marketplace artifact files.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files without writing them.",
    )
    return parser.parse_args()


def load_manifests() -> tuple[dict[str, Any], list[dict[str, Any]]]:
    root_manifest = load_yaml(ROOT_MANIFEST)
    plugin_names = root_manifest.get("plugins")
    if not isinstance(plugin_names, list) or not plugin_names:
        raise ValueError(".agent-marketplace.yaml must define a non-empty plugins list")

    plugins: list[dict[str, Any]] = []
    for plugin_name in plugin_names:
        if not isinstance(plugin_name, str) or not plugin_name:
            raise ValueError(".agent-marketplace.yaml plugins entries must be strings")
        manifest_path = PLUGIN_ROOT / plugin_name / "agent-plugin.yaml"
        plugin = load_yaml(manifest_path)
        plugin["_root"] = PLUGIN_ROOT / plugin_name
        plugin["_manifest_path"] = manifest_path
        plugins.append(plugin)
    return root_manifest, plugins


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        payload = parse_yaml(handle.read())
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a YAML object")
    return payload


def build_expected_files(
    root_manifest: dict[str, Any],
    plugins: list[dict[str, Any]],
) -> dict[Path, str | bytes]:
    expected: dict[Path, str | bytes] = {}
    expected[CLAUDE_MARKETPLACE] = json_text(build_claude_marketplace(root_manifest, plugins))
    expected[CODEX_MARKETPLACE] = json_text(build_codex_marketplace(root_manifest, plugins))

    for plugin in plugins:
        plugin_root = plugin["_root"]
        expected[plugin_root / "plugin.json"] = json_text(build_claude_plugin_json(plugin))
        expected[plugin_root / ".codex-plugin" / "plugin.json"] = json_text(
            build_codex_plugin_json(plugin)
        )

        for command_path in plugin.get("commands") or []:
            source = plugin_root / strip_dot(command_path)
            command_name = source.stem
            skill_dir = plugin_root / "skills" / f"{command_name}-command"
            expected[skill_dir / "SKILL.md"] = build_codex_command_skill(plugin, source)

            opencode_command = (
                OPENCODE_ROOT
                / plugin["name"]
                / ".opencode"
                / "commands"
                / source.name
            )
            expected[opencode_command] = build_opencode_command(plugin, source)

        for skill_path in plugin.get("skills") or []:
            source = plugin_root / strip_dot(skill_path)
            skill_root = source.parent
            opencode_skill_root = (
                OPENCODE_ROOT / plugin["name"] / ".opencode" / "skills" / skill_root.name
            )
            for child in sorted(skill_root.rglob("*")):
                if child.is_file():
                    relative = child.relative_to(skill_root)
                    expected[opencode_skill_root / relative] = child.read_bytes()

        for agent_path in plugin.get("agents") or []:
            source = plugin_root / strip_dot(agent_path)
            opencode_agent = (
                OPENCODE_ROOT
                / plugin["name"]
                / ".opencode"
                / "agent"
                / opencode_agent_filename(source)
            )
            expected[opencode_agent] = build_opencode_agent(plugin, source)

    return expected


def build_expected_executable_files(plugins: list[dict[str, Any]]) -> set[Path]:
    executable_files: set[Path] = set()
    for plugin in plugins:
        plugin_root = plugin["_root"]
        for skill_path in plugin.get("skills") or []:
            source = plugin_root / strip_dot(skill_path)
            skill_root = source.parent
            opencode_skill_root = (
                OPENCODE_ROOT / plugin["name"] / ".opencode" / "skills" / skill_root.name
            )
            for child in sorted(skill_root.rglob("*")):
                if child.is_file() and child.stat().st_mode & 0o111:
                    relative = child.relative_to(skill_root)
                    executable_files.add(opencode_skill_root / relative)
    return executable_files


def build_claude_marketplace(
    root_manifest: dict[str, Any],
    plugins: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "name": root_manifest["name"],
        "owner": root_manifest["owner"],
        "metadata": root_manifest["metadata"],
        "plugins": [build_claude_marketplace_entry(plugin) for plugin in plugins],
    }


def build_claude_marketplace_entry(plugin: dict[str, Any]) -> dict[str, Any]:
    plugin_root = plugin["_root"]
    source = f"./plugins/{plugin_root.name}"
    return {
        "name": plugin["name"],
        "source": source,
        "description": plugin.get("marketplace_description", plugin["description"]),
        "version": str(plugin["version"]),
        "author": plugin["author"],
        "homepage": plugin["homepage"],
        "repository": normalize_repository_for_marketplace(plugin["repository"]),
        "license": plugin["license"],
        "keywords": plugin.get("keywords", []),
        "category": plugin["category"],
        "tags": plugin.get("tags", []),
    }


def build_claude_plugin_json(plugin: dict[str, Any]) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "name": plugin["name"],
        "version": str(plugin["version"]),
        "description": plugin["description"],
        "author": plugin["author"],
        "homepage": plugin["homepage"],
        "repository": plugin["repository"],
        "license": plugin["license"],
        "keywords": plugin.get("keywords", []),
    }
    for key in ("commands", "skills", "agents"):
        values = plugin.get(key) or []
        if values:
            payload[key] = values
    return payload


def build_codex_marketplace(
    root_manifest: dict[str, Any],
    plugins: list[dict[str, Any]],
) -> dict[str, Any]:
    interface = root_manifest.get("interface") or {}
    return {
        "name": root_manifest["name"],
        "interface": {
            "displayName": interface.get("displayName", root_manifest["name"]),
        },
        "plugins": [build_codex_marketplace_entry(plugin) for plugin in plugins],
    }


def build_codex_marketplace_entry(plugin: dict[str, Any]) -> dict[str, Any]:
    plugin_root = plugin["_root"]
    return {
        "name": plugin["name"],
        "source": {
            "source": "local",
            "path": f"./plugins/{plugin_root.name}",
        },
        "policy": {
            "installation": "AVAILABLE",
            "authentication": "ON_INSTALL",
        },
        "category": target_value(plugin, "codex", "category", title_category(plugin["category"])),
    }


def build_codex_plugin_json(plugin: dict[str, Any]) -> dict[str, Any]:
    interface = plugin.get("interface") or {}
    developer_name = plugin["author"].get("name", "Datamaker")
    payload: dict[str, Any] = {
        "name": plugin["name"],
        "version": str(plugin["version"]),
        "description": plugin["description"],
        "author": plugin["author"],
        "homepage": plugin["homepage"],
        "repository": plugin["repository"],
        "license": plugin["license"],
        "keywords": plugin.get("keywords", []),
        "skills": "./skills/",
        "interface": {
            "displayName": interface.get("display_name", plugin["name"]),
            "shortDescription": interface.get("short_description", plugin["description"]),
            "longDescription": interface.get("long_description", plugin["description"]),
            "developerName": developer_name,
            "category": target_value(plugin, "codex", "category", title_category(plugin["category"])),
            "capabilities": interface.get("capabilities", []),
            "websiteURL": plugin["homepage"],
            "defaultPrompt": [interface.get("default_prompt", f"Help me use {plugin['name']}.")],
            "screenshots": [],
        },
    }
    return payload


def build_codex_command_skill(plugin: dict[str, Any], source: Path) -> str:
    frontmatter, body = read_markdown(source)
    command_name = source.stem
    description = frontmatter.get("description") or f"Run the {command_name} workflow."
    adapted_body = adapt_claude_command_body(body)
    skill_description = (
        f"Run the `{plugin['name']}:{command_name}` workflow from the original Claude slash "
        f"command. Use when the user asks to {lowercase_first(str(description))}"
    )
    return "\n".join(
        [
            "---",
            f"name: {command_name}-command",
            f"description: {yaml_string(skill_description)}",
            "---",
            "",
            GENERATED_NOTE,
            "",
            f"# {plugin['name']}:{command_name} Command Workflow",
            "",
            "## Codex Adaptation",
            "",
            "- Treat the user request or explicitly supplied text as the command arguments.",
            "- Use the available Codex file, search, terminal, and clarification capabilities that match the workflow.",
            "- Do not depend on Claude-only slash command variables or tool names.",
            "",
            adapted_body.strip(),
            "",
        ]
    )


def build_opencode_command(plugin: dict[str, Any], source: Path) -> str:
    frontmatter, body = read_markdown(source)
    description = frontmatter.get("description") or f"Run {source.stem}."
    adapted_body = adapt_claude_command_body(body)
    return "\n".join(
        [
            "---",
            f"description: {yaml_string(str(description))}",
            "---",
            "",
            GENERATED_NOTE,
            "",
            f"# {plugin['name']}:{source.stem}",
            "",
            "Use this command workflow in OpenCode. Treat prompt text after the command as the arguments.",
            "",
            adapted_body.strip(),
            "",
        ]
    )


def build_opencode_agent(plugin: dict[str, Any], source: Path) -> str:
    frontmatter, body = read_markdown(source)
    description = frontmatter.get("description") or f"Use the {source.stem} agent workflow."
    agent_name = frontmatter.get("name") or source.stem
    return "\n".join(
        [
            "---",
            f"description: {yaml_string(str(description))}",
            "---",
            "",
            GENERATED_NOTE,
            "",
            f"# {agent_name}",
            "",
            f"Source plugin: `{plugin['name']}`.",
            "",
            adapt_claude_command_body(body).strip(),
            "",
        ]
    )


def read_markdown(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    raw_frontmatter = text[4:end]
    body = text[end + len("\n---") :]
    frontmatter = extract_frontmatter_fields(raw_frontmatter)
    return frontmatter, body.lstrip("\n")


def extract_frontmatter_fields(raw_frontmatter: str) -> dict[str, Any]:
    fields: dict[str, Any] = {}
    lines = raw_frontmatter.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip() or line.startswith(" ") or ":" not in line:
            index += 1
            continue
        key, raw_value = line.split(":", 1)
        key = key.strip()
        value = raw_value.strip()
        if value in {">", "|"}:
            block_values: list[str] = []
            index += 1
            while index < len(lines) and (
                lines[index].startswith(" ") or not lines[index].strip()
            ):
                if lines[index].strip():
                    block_values.append(lines[index].strip())
                index += 1
            fields[key] = " ".join(block_values).strip()
            continue
        if value:
            fields[key] = parse_yaml_scalar(value)
        index += 1
    return fields


def parse_yaml(text: str) -> Any:
    """Parse the small YAML subset used by this repo's manifests/frontmatter."""
    lines = preprocess_yaml_lines(text)
    if not lines:
        return {}
    value, index = parse_yaml_block(lines, 0, lines[0][0])
    if index != len(lines):
        raise ValueError("unexpected trailing YAML content")
    return value


def preprocess_yaml_lines(text: str) -> list[tuple[int, str]]:
    parsed: list[tuple[int, str]] = []
    for raw_line in text.splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        parsed.append((indent, raw_line.strip()))
    return parsed


def parse_yaml_block(
    lines: list[tuple[int, str]],
    index: int,
    indent: int,
) -> tuple[Any, int]:
    if index >= len(lines):
        return {}, index
    if lines[index][1].startswith("- "):
        values: list[Any] = []
        while index < len(lines) and lines[index][0] == indent and lines[index][1].startswith("- "):
            item = lines[index][1][2:].strip()
            if not item:
                nested, index = parse_yaml_block(lines, index + 1, indent + 2)
                values.append(nested)
            else:
                values.append(parse_yaml_scalar(item))
                index += 1
        return values, index

    payload: dict[str, Any] = {}
    while index < len(lines) and lines[index][0] == indent and not lines[index][1].startswith("- "):
        key, sep, raw_value = lines[index][1].partition(":")
        if not sep:
            raise ValueError(f"invalid YAML line: {lines[index][1]}")
        key = key.strip()
        raw_value = raw_value.strip()
        if raw_value in {">", "|"}:
            value, index = parse_yaml_block_scalar(lines, index + 1, indent)
            payload[key] = value
        elif raw_value:
            payload[key] = parse_yaml_scalar(raw_value)
            index += 1
        else:
            if index + 1 >= len(lines) or lines[index + 1][0] <= indent:
                payload[key] = {}
                index += 1
            else:
                value, index = parse_yaml_block(lines, index + 1, lines[index + 1][0])
                payload[key] = value
    return payload, index


def parse_yaml_block_scalar(
    lines: list[tuple[int, str]],
    index: int,
    parent_indent: int,
) -> tuple[str, int]:
    values: list[str] = []
    while index < len(lines) and lines[index][0] > parent_indent:
        values.append(lines[index][1])
        index += 1
    return " ".join(values).strip(), index


def parse_yaml_scalar(value: str) -> Any:
    if value == "[]":
        return []
    if value == "{}":
        return {}
    if value in {"true", "True"}:
        return True
    if value in {"false", "False"}:
        return False
    if value in {"null", "Null", "~"}:
        return None
    if value.startswith("[") and value.endswith("]"):
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            return [item.strip().strip("\"'") for item in value[1:-1].split(",") if item.strip()]
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            return value[1:-1]
    return value


def adapt_claude_command_body(body: str) -> str:
    replacements = {
        "$ARGUMENTS": "the user request or explicit arguments",
        "AskUserQuestion": "ask the user a concise clarification",
        "TodoWrite": "maintain a task checklist",
        "allowed-tools": "available capabilities",
        "Claude Code": "the active coding agent",
    }
    adapted = body
    for source, target in replacements.items():
        adapted = adapted.replace(source, target)
    return adapted


def check_expected_files(
    expected: dict[Path, str | bytes],
    executable_files: set[Path],
) -> list[str]:
    failures: list[str] = []
    for path, expected_content in sorted(expected.items(), key=lambda item: str(item[0])):
        if not path.exists():
            failures.append(f"Missing generated file: {path.relative_to(ROOT)}")
            continue
        actual = path.read_bytes()
        expected_bytes = to_bytes(expected_content)
        if actual != expected_bytes:
            failures.append(diff_message(path, actual, expected_bytes))
        expected_executable = path in executable_files
        actual_executable = bool(path.stat().st_mode & 0o111)
        if expected_executable != actual_executable:
            mode = "executable" if expected_executable else "non-executable"
            failures.append(f"Generated file mode differs: {path.relative_to(ROOT)} should be {mode}")
    return failures


def diff_message(path: Path, actual: bytes, expected: bytes) -> str:
    relative = path.relative_to(ROOT)
    try:
        actual_text = actual.decode("utf-8").splitlines()
        expected_text = expected.decode("utf-8").splitlines()
    except UnicodeDecodeError:
        return f"Generated binary file differs: {relative}"
    diff = "\n".join(
        difflib.unified_diff(
            actual_text,
            expected_text,
            fromfile=f"{relative} (actual)",
            tofile=f"{relative} (expected)",
            lineterm="",
        )
    )
    return f"Generated file differs: {relative}\n{diff}"


def write_file(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(to_bytes(content))


def apply_executable_modes(executable_files: set[Path]) -> None:
    for path in executable_files:
        current = path.stat().st_mode
        path.chmod(current | 0o755)


def to_bytes(content: str | bytes) -> bytes:
    if isinstance(content, bytes):
        return content
    return content.encode("utf-8")


def copy_opencode_skill_assets(plugins: list[dict[str, Any]]) -> None:
    # Skill trees are already included in expected files. This hook exists to make the
    # generated ownership of dist/opencode explicit after the clean step.
    for plugin in plugins:
        (OPENCODE_ROOT / plugin["name"] / ".opencode").mkdir(parents=True, exist_ok=True)


def opencode_agent_filename(source: Path) -> str:
    if source.name == "SKILL.md":
        return f"{source.parent.name}.md"
    return source.name


def strip_dot(raw_path: str) -> Path:
    return Path(raw_path[2:] if raw_path.startswith("./") else raw_path)


def json_text(payload: dict[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def lowercase_first(value: str) -> str:
    if not value:
        return value
    return value[0].lower() + value[1:]


def title_category(value: str) -> str:
    return " ".join(part.capitalize() for part in value.replace("_", "-").split("-"))


def target_value(plugin: dict[str, Any], target: str, key: str, default: Any) -> Any:
    targets = plugin.get("targets") or {}
    target_payload = targets.get(target) or {}
    return target_payload.get(key, default)


def normalize_repository_for_marketplace(repository: str) -> str:
    return repository[:-4] if repository.endswith(".git") else repository


if __name__ == "__main__":
    main()
